Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - method_call
Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - method_call
TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
