plugins:
  - rubocop-rspec
AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    # rspec blocks can get very long
    - 'spec/**/*'
Metrics/ClassLength:
  Exclude:
    # our spec Classes can get very long
    - 'spec/**/*'
Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - method_call
Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - method_call
Naming/VariableNumber:
  EnforcedStyle: snake_case
RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - method_call
RSpec/NestedGroups:
  Max: 4
RSpec/RepeatedExample:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
