TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
